export type UserProfile = {
  id: string;
  email: string;
  full_name: string | null;
  company_name: string | null;
  plan: string;
  downloads_used: number;
  created_at: string;
  updated_at: string;
  avatar_url: string | null;
  phone: string | null;
  legal_name: string | null;
  tax_id: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  state: string | null;
  postal_code: string | null;
  country: string | null;
  website: string | null;
  logo_url: string | null;
  default_currency: string;
  default_payment_terms: string | null;
  invoice_footer: string | null;
  brand_color: string | null;
  default_template: string | null;
  bank_name: string | null;
  bank_account_name: string | null;
  bank_account_number: string | null;
  bank_swift: string | null;
  paypal_email: string | null;
  notify_on_view: boolean;
  notify_weekly: boolean;
};
